#!/usr/bin/env bash

repo="/usr/local/lib/cheatsheets.txt"

while IFS='' read -r line || [[ -n "$line" ]]; do
    if [[ $line = "$1="* ]] 
        then
            open ${line#*=}
    fi 
done < $repo
