#!/usr/bin/env bash

repo="/usr/local/lib/cheatsheets.txt"
while IFS='' read -r line || [[ -n "$line" ]]; do
    if [ $1 = '-l' ]
        then
            echo ${line%%=*}

    elif [[ $line = "$1="* ]]
        then
            open ${line#*=}
    fi 
done < $repo
